Import Modules needed

In [1]:
import numpy as np
import pandas as pd
#to find features of test data
import os
import featurefinder
#plot graphs module
import matplotlib.pyplot as plt
#Normalisation modules
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler
# Classifier module
from sklearn.neighbors import RadiusNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.preprocessing import LabelEncoder

Load Training Dataset with Features Extracted

In [2]:
dfTrainingData = pd.read_csv('Data/Train_features.csv')

K Radius Nearest Neighbors Classification

```
Note: in iloc format is [intial row: last row, intial column : last column]
```
Split training data

In [7]:
df = dfTrainingData.iloc[:,:-1]
task = dfTrainingData.iloc[:,-1:]

print(task)

cols = [col for col in df.columns if col not in ['Acc_X-71-JM','Acc_Y-71-JM','Acc_Z-71-JM','Gyr_X-71-JM','Gyr_Y-71-JM','Gyr_Z-71-JM','Acc_X-77-JM','Acc_Y-77-JM','Acc_Z-77-JM','Gyr_X-77-JM','Gyr_Y-77-JM','Gyr_Z-77-JM','Acc_X-71-PN','Acc_Y-71-PN','Acc_Z-71-PN','Gyr_X-71-PN','Gyr_Y-71-PN','Gyr_Z-71-PN','Acc_X-77-PN','Acc_Y-77-PN','Acc_Z-77-PN','Gyr_X-77-PN','Gyr_Y-77-PN','Gyr_Z-77-PN']]
features = df[cols]

le = LabelEncoder()
features.iloc[:,-1] = le.fit_transform(features.iloc[:,-1])

X_train, X_test, y_train, y_test = train_test_split(features, task, test_size = 0.20)
#We are performing a train test split on the dataset. We are providing the test size as 0.20, that means our training sample contains 320 training set and test sample contains 80 test set

# 'Acc_X-71-JM','Acc_Y-71-JM','Acc_Z-71-JM','Gyr_X-71-JM','Gyr_Y-71-JM','Gyr_Z-71-JM','Acc_X-77-JM','Acc_Y-77-JM','Acc_Z-77-JM','Gyr_X-77-JM','Gyr_Y-77-JM','Gyr_Z-77-JM'
# 'Acc_X-71-PN','Acc_Y-71-PN','Acc_Z-71-PN','Gyr_X-71-PN','Gyr_Y-71-PN','Gyr_Z-71-PN','Acc_X-77-PN','Acc_Y-77-PN','Acc_Z-77-PN','Gyr_X-77-PN','Gyr_Y-77-PN','Gyr_Z-77-PN'


# print(features)

        Task
0       Lift
1       Lift
2       Lift
3       Lift
4       Lift
...      ...
1498  Rotate
1499  Rotate
1500  Rotate
1501  Rotate
1502  Rotate

[1503 rows x 1 columns]


D:\software\Python37\lib\site-packages\pandas\core\indexing.py:1773: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)


Create Classifer Model: 

In [6]:
# create the model
model = RadiusNeighborsClassifier()

# create pipeline
pipeline = Pipeline(steps=[('norm', MinMaxScaler()),('model',model)])


#fit model
pipeline.fit(X_train,np.ravel(y_train))

Pipeline(steps=[('norm', MinMaxScaler()),
                ('model', RadiusNeighborsClassifier())])

Loading Testing Data and using classifer to predict Validation measurements

In [7]:
i = 0
correctMatch = 0
incorrectMatch = 0

incorrectMatchLift= 0
incorrectMatchRnR = 0
incorrectMatchSwing = 0 
incorrectMatchRotate = 0


# make a prediction
yhat = pipeline.predict(X_test)

# find confusion matrix
cm = confusion_matrix(y_test, yhat)
ac = accuracy_score(y_test,yhat)

print('Confusion matrix is: %s' % cm)
print('Accuracy score is: %f' % ac)



# print('Test Number: %d' % i)
# i = i + 1
# summarize prediction
# print('Predicted Class: %s' % yhat)
# print('Actual Class: %s' % )

# for folder in os.listdir("Data/Predict/"):
#     path = "Data/Predict/" + folder + "/"
#     for file in os.listdir(path):
#         pathfile = "Data/Predict/" + folder + "/"
#         Stan_Dev_names_U, RMS_names_U, Entropy_names_U, JM_names_U, PN_names_U, Stan_Dev_values_U, RMS_values_U,Entropy_values_U, JM_values_U, PN_values_U,Stan_Dev_values_L, RMS_values_L,  Entropy_values_L, JM_values_L, PN_values_L,Stan_Dev_names_L,RMS_names_L, Entropy_names_L, JM_names_L, PN_names_L = featurefinder.FeatureFinder(file,pathfile)
#         if (len(Stan_Dev_values_L) > 0 ):
#             # F_Names = Stan_Dev_names_L + RMS_names_L + Entropy_names_L + JM_names_L + PN_names_L + Stan_Dev_names_U + RMS_names_U + Entropy_names_U + JM_names_U + PN_names_U
#             # F_Values = Stan_Dev_values_L + RMS_values_L + Entropy_values_L + JM_values_L + PN_values_L + Stan_Dev_values_U + RMS_values_U + Entropy_values_U + JM_values_U + PN_values_U
#             F_Names = Stan_Dev_names_L + RMS_names_L + Entropy_names_L  + Stan_Dev_names_U + RMS_names_U + Entropy_names_U
#             F_Values = Stan_Dev_values_L + RMS_values_L + Entropy_values_L  + Stan_Dev_values_U + RMS_values_U + Entropy_values_U
#             dfFeaturesTest =  pd.DataFrame([],columns=F_Names)
#             dfFeaturesTest.loc[len(dfFeaturesTest)] = F_Values
#             # make a prediction
#             yhat = pipeline.predict(dfFeaturesTest)
#             # print('Test Number: %d' % i)
#             i = i + 1
#             # # summarize prediction
#             # print('Predicted Class: %s' % yhat)
#             # print('Actual Class: %s' % folder)
#             if (str(yhat)[2:-2] == str(folder)):
#                 correctMatch = correctMatch + 1
#             else:
# from sklearn.metrics import confusion_matrix,accuracy_score
# cm = confusion_matrix(y_test, y_pred)
# ac = accuracy_score(y_test,y_pred)
#                 incorrectMatch = incorrectMatch + 1
#                 if folder == 'Lift':
#                     incorrectMatchLift = incorrectMatchLift + 1
#                 elif folder == 'R&r':
#                     incorrectMatchRnR = incorrectMatchRnR + 1
#                     print("IS R&R --> Thinks is %s" % str(yhat)[2:-2])
#                 elif folder == 'Rotate':
#                     incorrectMatchRotate = incorrectMatchRotate + 1
#                 elif folder == 'Swing':
#                     incorrectMatchSwing = incorrectMatchSwing + 1
#                 else:
#                     pass
#         else:
#             pass

Confusion matrix is: [[52 22  0  8]
 [23 46  4  5]
 [ 5 14 49  3]
 [ 0  1  1 68]]
Accuracy score is: 0.714286


In [8]:
# print("Correct matches are : %d " % correctMatch)
# print("Incorrect matches are : %d " % incorrectMatch)
# n = i + 1
# Accuracy = (correctMatch/n)*100
# print("Accuracy Percentage : %f " % Accuracy)
# print("Incorrect matches for Lift are : %d " % incorrectMatchLift)
# print("Incorrect matches for R&R are : %d " % incorrectMatchRnR)
# print("Incorrect matches for Swing are : %d " % incorrectMatchSwing)
# print("Incorrect matches for Rotate are : %d " % incorrectMatchRotate)
# # yat = "['Lift']"
# print(yat[2:-2])